### PR TITLE
Style

### PR DESCRIPTION
**Pull request by CumpsD**
Went over the entire codebase with Resharper to cleanup some style and change access levels.

Next step will be some refactorings to split up some of the bigger classes.

### CODE REVIEW

**Comment by abelsilva** [comment]
do you any IP Routing/Interface to test everything?

**Comment by CumpsD** [comment]
I tested it with `KnxConnectionRouting` and it worked :)

**Comment by CumpsD** [comment]
and `KnxConnectionTunneling` worked too

**Comment by abelsilva** [comment]
Nice! :+1: 

Thanks for letting me know

**Pull request merged**
